### PR TITLE
Populate RepositoryBranch package metadata if available

### PR DESCRIPTION
**Pull request by kzu**
Only do so if PublishRepositoryUrl=true, meaning you want this information to be public in the first place.

See RepositoryBranch in https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets.

### CODE REVIEW

**Comment by baronfel** [comment]
This seems very reasonable, but I have to admit that my first thought was 'why isn't this in dotnet/sourcebuild?'. I looked in that repo and they don't do anything for RepositoryBranch, so I was surprised.

**Review by baronfel — APPROVED** [review]
This LGTM baased on the linked CI systems, but I'd appreciate Claire's look at it as well.

**Comment by kzu** [comment]
Gently pinging @clairernovotny 😉

**Comment by kzu** [comment]
Anything stopping this PR from merging? Polysharp also waiting on this ... https://github.com/Sergio0694/PolySharp/pull/24#discussion_r1024511185 

@clairernovotny ?

**Comment by clairernovotny** [comment]
@baronfel ?

**Comment by baronfel** [comment]
Thanks @kzu, and sorry for this one falling through the cracks.

**Comment by kzu** [comment]
How does this ship? Is it automatic? Did it ship already?

**Comment by kzu** [comment]
This still hasn't shipped: https://www.nuget.org/packages/DotNet.ReproducibleBuilds

**Comment by baronfel** [comment]
We've shipped this in 1.2.4 at long last!

**Pull request merged**
